language: python

python:
    - "3.6"
    - "3.7"
env:
    - SECRET_KEY='TEST'
services:
    - postgresql
install:
    - pipenv install
    - pip install -r requirements.txt
    
script:
    - python manage.py test