# Generated by Django 2.2.1 on 2020-03-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id_kabupaten', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=128)),
                ('lat', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Penderita',
            fields=[
                ('id_penderita', models.AutoField(primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('laki-laki', 'LAKI-LAKI'), ('perempuan', 'PEREMPUAN')], default='laki-laki', max_length=15)),
                ('status', models.CharField(choices=[('sembuh', 'SEMBUH'), ('meninggal', 'MENINGGAL')], default='sembuh', max_length=15)),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbackend.Kabupaten')),
            ],
        ),
    ]
