# Generated by Django 2.2.8 on 2020-04-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0002_auto_20200402_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='penderita',
            name='umur',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='penderita',
            name='gender',
            field=models.CharField(choices=[('Laki-Laki', 'LAKI-LAKI'), ('Perempuan', 'PEREMPUAN')], default='laki-laki', max_length=15),
        ),
        migrations.AlterField(
            model_name='penderita',
            name='status',
            field=models.CharField(choices=[('Sembuh', 'SEMBUH'), ('Meninggal', 'MENINGGAL'), ('Positif', 'POSITIF')], default='sembuh', max_length=15),
        ),
    ]
