# Generated by Django 2.2.8 on 2020-04-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0004_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='penderita',
            name='nomor',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
