# Generated by Django 2.2.8 on 2020-04-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0005_penderita_nomor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odp',
            fields=[
                ('id_odp', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=10)),
                ('nama_orang', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Laki-Laki', 'LAKI-LAKI'), ('Perempuan', 'PEREMPUAN')], default='laki-laki', max_length=15)),
                ('alamat', models.CharField(max_length=250)),
                ('no_kontak', models.CharField(max_length=20)),
                ('mulai_dp', models.DateField()),
                ('berakhir_dp', models.DateField()),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbackend.Kabupaten')),
            ],
            options={
                'ordering': ('id_odp',),
            },
        ),
    ]
