# Generated by Django 2.2.8 on 2020-04-22 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0006_odp'),
    ]

    operations = [
        migrations.AddField(
            model_name='odp',
            name='umur',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='penderita',
            name='rs',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appbackend.Rumah_sakit'),
        ),
        migrations.CreateModel(
            name='Pdp',
            fields=[
                ('id_pdp', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Laki-Laki', 'LAKI-LAKI'), ('Perempuan', 'PEREMPUAN')], default='laki-laki', max_length=15)),
                ('umur', models.CharField(blank=True, max_length=10)),
                ('alamat', models.CharField(max_length=250)),
                ('no_kontak', models.CharField(max_length=20)),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbackend.Kabupaten')),
                ('rs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbackend.Rumah_sakit')),
            ],
            options={
                'ordering': ('id_pdp',),
            },
        ),
    ]
