# Generated by Django 2.2.8 on 2020-04-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0007_auto_20200422_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='odp',
            name='status_opd',
            field=models.CharField(choices=[('Selesai', 'SELESAI'), ('Belum', 'BELUM')], default='Belum', max_length=15),
        ),
        migrations.AddField(
            model_name='pdp',
            name='status_pdp',
            field=models.CharField(choices=[('Positif', 'POSITIF'), ('Negatif', 'NEGATIF')], default='Negatif', max_length=15),
        ),
    ]
